Br.Scania.ExternalAGV.WebUI/Models/ErrorViewModel.cs
using System;

namespace Br.Scania.ExternalAGV.WebUI.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Br.Scania.ExternalAGV.WebUI/Controllers/AGVController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace Br.Scania.ExternalAGV.WebUI.Controllers
{
    public class AGVController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Monitor()
        {
            return View();
        }
    }
}

Br.Scania.ExternalAGV.WebUI/Controllers/ChamadasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace Br.Scania.ExternalAGV.WebUI.Controllers
{
    public class ChamadasController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Br.Scania.ExternalAGV.WebUI/Controllers/ConfigPointsAuxController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace Br.Scania.ExternalAGV.WebUI.Controllers
{
    public class ConfigPointsAuxController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Br.Scania.ExternalAGV.WebUI/Controllers/ConfigPointsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace Br.Scania.ExternalAGV.WebUI.Controllers
{
    public class ConfigPointsController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Br.Scania.ExternalAGV.WebUI/Controllers/ControlTowerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace Br.Scania.ExternalAGV.WebUI.Controllers
{
    public class ControlTowerController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Br.Scania.ExternalAGV.WebUI/Controllers/EquipmentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace Br.Scania.ExternalAGV.WebUI.Controllers
{

    public class EquipmentController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

    }
}

Br.Scania.ExternalAGV.WebUI/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Br.Scania.ExternalAGV.WebUI.Models;

namespace Br.Scania.ExternalAGV.WebUI.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Br.Scania.ExternalAGV.WebUI/Controllers/RouteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace Br.Scania.ExternalAGV.WebUI.Controllers
{
    public class RouteController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Br.Scania.ExternalAGV.WebUI/Views/AGV/Index.cshtml
@{
    ViewData["Title"] = "Gravar Rota";
}

<link href="~/css/agv.css" rel="stylesheet" />
<link href="~/css/leaflet.css" rel="stylesheet" />
<link href="~/css/leaflet_awesome_number_markers.css" rel="stylesheet" />
<link href="~/css/site.css" rel="stylesheet" />

<div class="row">
    <div class="col-lg-2" style="border:solid;">
        <h4>Clique duplo para transferir a rota!</h4>
        <table class="table table-hover" id="bodyTabela">
            <thead>
                <tr>
                    <th><h4>Rota</h4></th>
                </tr>
            </thead>
            <tbody></tbody>
        </table>
    </div>
    <div class="col-lg-2" style="border:solid">
        <table class="table table-hover" id="bodyTabelaRoute">
            <thead>
                <tr>
                    <th><h4>Descrição</h4></th>
                </tr>
            </thead>
            <tbody></tbody>
        </table>
        <div id="button-update"></div>
    </div>
    <div id="map"></div>
</div>

<script src="~/lib/jquery/dist/jquery.js"></script>
<script src="~/lib/leaflet/leaflet-0.7.3.js"></script>
<script src="~/js/leaflet_awesome_number_markers.js"></script>
<script src="~/js/agv.js"></script>

Br.Scania.ExternalAGV.WebUI/Views/AGV/Monitor.cshtml
@{
    ViewData["Title"] = "Monitoramento de Rota";
}

<link href="~/css/monitor.css" rel="stylesheet" />
<link href="~/css/leaflet.css" rel="stylesheet" />
<link href="~/css/leaflet_awesome_number_markers.css" rel="stylesheet" />
<link href="~/css/site.css" rel="stylesheet" />

<div class="row">
    <div class="col-3" style="overflow-y: auto; border:solid;" >
        <table class="table table-hover" id="bodyTabelaRoute">
            <thead>
                <tr>
                    <th><h4>Descrição</h4></th>
                </tr>
            </thead>
            <tbody></tbody>
        </table>
        <div id="button-update"></div>
    </div>
    <div style="overflow-y: auto;" id="map"></div>
</div>

<script src="~/lib/jquery/dist/jquery.js"></script>
<script src="~/lib/leaflet/leaflet-0.7.3.js"></script>
<script src="~/js/leaflet_awesome_number_markers.js"></script>
<script src="~/js/monitor.js"></script>

Br.Scania.ExternalAGV.WebUI/Views/ConfigPoints/Index.cshtml
@{
    ViewData["Title"] = "Gravação de Pontos";
}

<link href="~/css/configPoints.css" rel="stylesheet" />
<link href="~/css/leaflet.css" rel="stylesheet" />
<link href="~/css/leaflet_awesome_number_markers.css" rel="stylesheet" />
<link href="~/css/site.css" rel="stylesheet" />


<div class="row">
    <div id="map"></div>
    <div>
        <div>
            <div class="row">
                <div>
                    <button type="button" class="btn btn-success btn-success-save" id="btn-insert-point">Criar Novo</button>
                </div>
                <div class="position">
                    <div class="row">
                        <div style="width:100px">Latitude:</div>
                        <div id="latValue">000000</div>
                    </div>
                    <div class="row">
                        <div style="width:100px">Longitude:</div>
                        <div id="lngValue">000000</div>
                    </div>
                </div>
            </div>
        </div>
        <div>
            <table class="table table-hover" id="bodyTabela">
                <thead>
                    <tr>
                        <th><h4>Descrição</h4></th>
                        <th><h4>Latitude</h4></th>
                        <th><h4>Longitude</h4></th>
                        <th><h4>Velocidade</h4></th>
                        <th><h4>Seta</h4></th>
                        <th><h4>Trajeto</h4></th>
                    </tr>
                </thead>
                <tbody></tbody>
            </table>
        </div>
    </div>
</div>

<div class="modal modalLatLng fade" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="modalTitle">INSERT POINT</h4>
            </div>
            <input type="hidden" id="modal-id">
            <div class="modal-body">
                <div class="row">
                    <div class="col-md-12">
                        <label class="col-md-4" for="tittle">Descrição</label>
                        <input class="col-md-6 datetimepicker" id="modal-description" type="text">
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <input class="col-md-6 datetimepicker" id="modal-lon" type="hidden">
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <input class="col-md-6 datetimepicker" id="modal-lat" type="hidden">
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-12">
                        <label class="col-md-4" for="tittle">Corrigir Coord</label>
                        <div class="form-check-inline">
                            <label class="form-check-label">
                                <input type="checkbox" class="form-check-input" id="update-coord" value:"false">
                            </label>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-12">
                        <label class="col-md-4" for="tittle">Velocidade</label>
                        <input class="col-md-6 datetimepicker" id="modal-velocity" type="text">
                    </div>
                </div>


                @*<div class="row">
                        <div class="col-md-12">
                            <label class="col-md-4" for="tittle">Icon</label>
                            <input class="col-md-6 datetimepicker" id="modal-icon" type="text">
                        </div>
                    </div>*@

                <div class="row">
                    <div class="col-md-12">
                        <label class="col-md-4" for="tittle">Seta</label>
                        <div class="form-check-inline">
                            <label class="form-check-label">
                                <input type="checkbox" class="form-check-input" id="modal-leftlight" value:"true">Esquerda
                            </label>
                        </div>
                        <div class="form-check-inline">
                            <label class="form-check-label">
                                <input type="checkbox" class="form-check-input" id="modal-rightlight" value:"true">Direita
                            </label>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-12">
                        <label class="col-md-4" for="tittle">Trajeto</label>
                        <div class="form-check-inline">
                            <label class="form-check-label">
                                <input type="checkbox" class="form-check-input" id="modal-onstraight-straight" value:"true">Reta
                            </label>
                        </div>
                        <div class="form-check-inline">
                            <label class="form-check-label">
                                <input type="checkbox" class="form-check-input" id="modal-onstraight-turn" value:"true">Curva
                            </label>
                        </div>
                    </div>
                </div>

            </div>



            <div class="modal-footer">
                <button type="button" class="btn btn-default" id="cancel-event" data-dismiss="modal">Cancel</button>
                <button type="button" class="btn btn-success" id="insert-event">Insert</button>
                <button type="button" class="btn btn-danger" id="remove-event">Remove</button>

            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->



<script src="~/lib/jquery/dist/jquery.js"></script>
<script src="~/lib/leaflet/leaflet-0.7.3.js"></script>
<script src="~/js/leaflet_awesome_number_markers.js"></script>
<script src="~/js/configPoints.js"></script>

Br.Scania.ExternalAGV.WebUI/Views/ConfigPointsAux/Index.cshtml
@{
    ViewData["Title"] = "Gravação de Pontos";
}

<link href="~/css/configPoints.css" rel="stylesheet" />
<link href="~/css/leaflet.css" rel="stylesheet" />
<link href="~/css/leaflet_awesome_number_markers.css" rel="stylesheet" />
<link href="~/css/site.css" rel="stylesheet" />

<div id="text">   </div>

<script src="~/lib/jquery/dist/jquery.js"></script>
<script src="~/lib/leaflet/leaflet-0.7.3.js"></script>
<script src="~/js/leaflet_awesome_number_markers.js"></script>
<script src="~/js/configPointsAux.js"></script>

Br.Scania.ExternalAGV.WebUI/Views/Equipment/Index.cshtml
@{
    ViewData["Title"] = "Equipamento";
}

<link href="~/css/equipment.css" rel="stylesheet" />
<link href="~/css/site.css" rel="stylesheet" />

<div class="row">
    <div class="col-3">
        <button type="button" class="btn btn-success" id="insert-event">Insert</button>
        <table class="table table-hover" id="bodyTabela">
            <thead>
                <tr>
                    <th><h4>ID</h4></th>
                    <th><h4>Equipamento</h4></th>
                </tr>
            </thead>
            <tbody></tbody>
        </table>
    </div>
</div>



<div class="modal modalLatLng fade" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="modalTitle">Dados do Equipamento</h4>
            </div>
            <input type="hidden" id="id">
            <div class="modal-body">
                <div class="input-group mb-3">
                    <div class="col-5">
                        <h4>Tipo:</h4>
                    </div>
                    <div class="col-7">
                        <input id="type" type="text" class="form-control" placeholder="" aria-label="" aria-describedby="basic-addon1">
                    </div>
                </div>
                <div class="input-group mb-3">
                    <div class="col-5">
                        <h4>Número:</h4>
                    </div>
                    <div class="col-7">
                        <input id="equipNumber" type="text" class="form-control" placeholder="" aria-label="" aria-describedby="basic-addon1">
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" id="cancel-event" data-dismiss="modal">Cancel</button>
                <button type="button" class="btn btn-success" id="form-event"></button>
                <button type="button" class="btn btn-danger" id="remove-event">Remove</button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<script src="~/lib/jquery/dist/jquery.js"></script>
<script src="~/js/equipment.js"></script>

Br.Scania.ExternalAGV.WebUI/Views/Route/Index.cshtml
@{
    ViewData["Title"] = "Rotas";
}

<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
<link href="~/css/route.css" rel="stylesheet" />
<link href="~/css/site.css" rel="stylesheet" />

<div class="row">
    <div class="col-3" style="border:solid;height:650px;">
        <button type="button" class="btn btn-success" id="insert-event">Insert</button>
        <table class="table table-hover" id="bodyTabela">
            <thead>
                <tr>
                    <th><h4>Rota</h4></th>
                </tr>
            </thead>
            <tbody></tbody>
        </table>
    </div>
    <div class="col-4" style="border:solid">
        <table class="table table-hover" id="bodyTabelaConfig">
            <thead>
                <tr>
                    <th><h4>Descrição</h4></th>
                    @*<th><h4>Latitude</h4></th>
                        <th><h4>Longitude</h4></th>*@
                </tr>
            </thead>
            <tbody></tbody>
        </table>
    </div>
    <div class="col-5" style="border:solid">
        <div>
            <h4 id="routeName">Selecionar Rota</h4>
        </div>
        <table class="table table-hover" id="bodyTabelaRoute">
            <thead>
                <tr>
                    <th><h4>Descrição</h4></th>
                    @*<th><h4>Latitude</h4></th>
                        <th><h4>Longitude</h4></th>*@
                </tr>
            </thead>
            <tbody></tbody>
        </table>
        <div id="button-update"></div>
    </div>
</div>

<div class="modal modalLatLng fade" tabindex="-1" role="dialog" id="modalInsert">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="modalTitle"></h4>
            </div>
            <input type="hidden" id="id">
            <div class="modal-body">
                <div class="input-group mb-3">
                    <div class="col-5">
                        <h4 id="modalContent">@*Descrição:*@</h4>
                        <br>
                        <h4 id="modalContent2">@*Descrição:*@</h4>
                    </div>
                    <div class="col-7">
                        @*<input id="equipNumber" type="text" class="form-control" placeholder="" aria-label="" aria-describedby="basic-addon1">*@
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" id="cancel-event" data-dismiss="modal">Cancel</button>
                <button type="button" class="btn btn-success" id="form-event"></button>
                <button type="button" class="btn btn-danger" id="remove-event">Remove</button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

@*<div class="modal modalLatLng fade" tabindex="-1" role="dialog" id="modalPickUpPoint">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="modalTitle-RoutePickUpPoint">Rota <span id="modalTitle-RoutePickUpPointName"></span>></h4>
            </div>
            <input type="hidden" id="id">
            <div class="modal-body">
                <div class="input-group mb-3">
                    <div class="col-5">
                        <h4>Ponte de Coleta:</h4>
                    </div>
                    <div class="col-7">
                        <select id="select-Routepoint"></select>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" id="cancel-event" data-dismiss="modal">Cancel</button>
                <button type="button" class="btn btn-success" id="form-event"></button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->*@






<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<script src="~/js/route.js"></script>

Br.Scania.ExternalAGV.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - External AGV</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" />
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
        
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-1">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Config</a>
                            <div class="dropdown-menu">
                                <a class="dropdown-item" asp-area="" asp-controller="Equipment" asp-action="Index">Equipamento</a>
                                <a class="dropdown-item" asp-area="" asp-controller="ConfigPoints" asp-action="Index">Configuração de Pontos</a>
                                <a class="dropdown-item" asp-area="" asp-controller="Route" asp-action="Index">Rotas</a>
                            </div>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">AGV</a>
                            <div class="dropdown-menu">
                                <a class="dropdown-item" asp-area="" asp-controller="AGV" asp-action="Index">Gravar Rota</a>
                                <a class="dropdown-item" asp-area="" asp-controller="AGV" asp-action="Monitor">Monitorar Rota</a>
                                <a class="dropdown-item" asp-area="" asp-controller="AGV" asp-action="Status">Status</a>
                            </div>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Chamadas" asp-action="Index">Chamadas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ControlTower" asp-action="Index">ControlTower</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Parâmetros" asp-action="Index">Parâmetros</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container-fluid">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-0">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - Autonomous Smart Solutions - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>